services:
  - type: web
    name: smart-attendance
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: smart-attendance
          property: port
      - key: MONGO_URI
        sync: false
      - key: APP_BASE_URL
        sync: false


